### ISSUE TITLE
Display Mission Team Attendance 

### ISSUE THREAD

**Issue by Eric-Arellano** [Eric-Arellano/ngsc-service-hours#3]
This data needs to be dynamically pulled and presented from master spreadsheet. 

Need to create API endpoints + add relevant components.

**Comment by dchen97** [comment]
# Requirements
- [ ] Create API call to pull Mission team attendance data from master spreadsheet
- [ ] Display attendance data once user's ID is confirmed

-----
cc: @Eric-Arellano

**Comment by Eric-Arellano** [comment]
closed with PR #15
